/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BacklinksRouteImport } from './routes/backlinks'
import { Route as AuditsRouteImport } from './routes/audits'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklinksRoute = BacklinksRouteImport.update({
  id: '/backlinks',
  path: '/backlinks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsRoute = AuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/backlinks': typeof BacklinksRoute
  '/campaigns': typeof CampaignsRoute
  '/competitors': typeof CompetitorsRoute
  '/keywords': typeof KeywordsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/backlinks': typeof BacklinksRoute
  '/campaigns': typeof CampaignsRoute
  '/competitors': typeof CompetitorsRoute
  '/keywords': typeof KeywordsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/backlinks': typeof BacklinksRoute
  '/campaigns': typeof CampaignsRoute
  '/competitors': typeof CompetitorsRoute
  '/keywords': typeof KeywordsRoute
  '/projects': typeof ProjectsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audits'
    | '/backlinks'
    | '/campaigns'
    | '/competitors'
    | '/keywords'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audits'
    | '/backlinks'
    | '/campaigns'
    | '/competitors'
    | '/keywords'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/audits'
    | '/backlinks'
    | '/campaigns'
    | '/competitors'
    | '/keywords'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditsRoute: typeof AuditsRoute
  BacklinksRoute: typeof BacklinksRoute
  CampaignsRoute: typeof CampaignsRoute
  CompetitorsRoute: typeof CompetitorsRoute
  KeywordsRoute: typeof KeywordsRoute
  ProjectsRoute: typeof ProjectsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlinks': {
      id: '/backlinks'
      path: '/backlinks'
      fullPath: '/backlinks'
      preLoaderRoute: typeof BacklinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits': {
      id: '/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditsRoute: AuditsRoute,
  BacklinksRoute: BacklinksRoute,
  CampaignsRoute: CampaignsRoute,
  CompetitorsRoute: CompetitorsRoute,
  KeywordsRoute: KeywordsRoute,
  ProjectsRoute: ProjectsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
